.\" Written by Sébastien Millet
.\"
.TH netmon 1 "version 1.1" "September 2013"

.SH NAME
.TP
netmon \- a program to monitor remote TCP ports

.SH SYNOPSIS
.TP
\fBnetmon\fP [-c config-file] [-l log-file] [\fIOPTIONS\fP]...
.TP
Linux: run \fBnetmon\fP "as is" or with -d option for daemon-style.
.TP
Windows: run \fBnetmon.exe --install\fP to install netmon as a Windows service,
allowing automatic startup when Windows starts, without session opening.

.SH DESCRIPTION
.TP
netmon is meant to do TCP connection tests at regular intervals, and publish the status in an HTML page. It manages emails loops - sending emails and checking they're received on the target mail box, making sure the whole chain in between works fine.
.TP
netmon includes a minimalistic web server.

.SH OPTIONS
.TP
.B \-h,\ \-\-help
Display a quick help screen and exit
.TP
.B \-V\ \-\-version
Display version information and exit
.TP
.B \-v,\ \-\-verbose
Be more talkative, the more -v found, the more talkative
.TP
.B \-q,\ \-\-quiet
Be less talkative, the less -q found, the less talkative
.TP
.B \-l,\ \-\-log-file\ \fIlog-file\fP
Log information into \fIlog-file\fP. By default it is \fInetmon.log\fP
.TP
.B \-c,\ \-\-config-file\ \fIconfig-file\fP
Use \fIconfig-file\fP to read configuration. By default it is \fInetmon.ini\fP
.TP
.B \-p,\ \-\-print-log
Display log on the terminal
.TP
.B \-C,\ \-\-stdout
Display status information on the terminal
.TP
.B \-t,\ \-\-test \fIN\fP
Use test mode number \fIN\fP, for test suite only
.TP
.B \-a,\ \-\-alert \fIalert-name\fP
Test alert \fIalert-name\fP, then quit
.TP
.B \-\-laxist
Continue if errors are found in the config file (default: stop)
.TP
.B \-\-install
Install NT service (Windows only)
.TP
.B \-\-uninstall
Uninstall NT service (Windows only)
.TP
.B \-d,\ \-\-daemon
Runs as a daemon (Linux) or as a service (Windows)
.SH "INITIALIZATION FILES"
.TP
.B netmon.ini
Windows-like configuration file
.TP
.br
The file \fBnetmon\-sample.ini\fP, provided with netmon, contains all ini variables with a short help.
.TP
.br
