#!/bin/sh

#
# Convert raw data to C language source file
#

SRC="$1"
VAR=`echo $SRC | sed 's/.*\///;s/\..*//;s/-/_/g'`
DST=`echo $SRC | sed 's/\..*//'`.c

echo "// $DST" > $DST
echo >> $DST
echo "// Generated by rdtosrc.sh on "`date +%Y-%m-%d` >> $DST
echo "// (c) 2013 Sébastien Millet" >> $DST
echo >> $DST
echo "#include <stdlib.h>" >> $DST
echo >> $DST
echo "const char const $VAR[] = {" >> $DST
hexdump -v -e '16/1 "0x%02X, " "\n"' "$1" | sed 's/,\s*0x\s*,.*//;$s/,\s*$//' >> $DST
echo "};" >> $DST
echo >> $DST
echo "const size_t ${VAR}_len = sizeof($VAR);" >> $DST
echo >> $DST

