#!/bin/sh

N=netmon

SOURCE=../doc/${N}.html
TARGET=${N}.html.c

echo "// $TARGET" > $TARGET
echo >> $TARGET
echo "// Generated by build-embdoc.sh on "`date +%Y-%m-%d` >> $TARGET
echo "// (c) 2013, 2014, 2019 Sébastien Millet" >> $TARGET
echo >> $TARGET
echo "#include <stdlib.h>" >> $TARGET
echo >> $TARGET
echo "const char *${N}[] = {" >> $TARGET
sed 's/"/\\"/g;s/^/"/;s/$/",/' $SOURCE | sed '$s/,$//' >> $TARGET
echo "};" >> $TARGET
echo >> $TARGET
echo "const size_t ${N}_len = sizeof(${N}) / sizeof(*${N});" >> $TARGET
echo >> $TARGET
