#!/bin/sh

N=netmon

SOURCE=../doc/${N}.html
TARGET=${N}.html.c

echo "// $TARGET" > $TARGET
echo >> $TARGET
echo "// Generated by build-embdoc.sh on "`date +%Y-%m-%d` >> $TARGET
echo "// (c) 2013 Sébastien Millet" >> $TARGET
echo >> $TARGET
echo "#include <stdlib.h>" >> $TARGET
echo >> $TARGET
echo "const char *${N}[] = {" >> $TARGET
sed 's/^<A HREF="\/cgi-bin\/man\/man2html">Return to Main Contents<\/A><HR>$/ <A HREF="\/">Return to Main Contents<\/A><HR>/' $SOURCE | sed 's/"/\\"/g;s/^/"/;s/$/",/' | sed '$s/,$//' >> $TARGET
echo "};" >> $TARGET
echo >> $TARGET
echo "const size_t ${N}_len = sizeof(${N}) / sizeof(*${N});" >> $TARGET
echo >> $TARGET
